import analysis

print("Analysis for testfile1.txt")
analysis.load("testfile1.txt")
print("Getting total word count - should be 51")
print(analysis.countall())
print("Getting unique word count - should be 5")
print(analysis.countunique())
print("Getting common word out of ['apple','peach','pear'] - should be apple")
print(analysis.commonword(["apple","peach","pear"]))
print("Getting common word out of ['coconut','peach','banana'] - should be peach")
print(analysis.commonword(["coconut","peach","banana"]))
print("Getting common word out of ['pear','banana'] - should be pear")
print(analysis.commonword(["pear","banana"]))
print("Getting common word out of ['apple','peach','pear','coconut','banana'] - should be apple")
print(analysis.commonword(['apple','peach','pear','coconut','banana']))
print("Getting common word out of ['plum','orange'] - should be None")
print(analysis.commonword(['plum','orange']))
print("Getting common letter out of ['a','e','i','o','u'] - should be a")
print(analysis.commonletter(['a','e','i','o','u']))
print("Getting common letter out of ['c', 't', 'p'] - should be p")
print(analysis.commonletter(['c', 't', 'p']))
print("Getting common letter out of ['z','x','y'] - should be None")
print(analysis.commonletter(['z','x','y']))
print("Getting common pair for 'apple' - should be coconut or peach")
print(analysis.commonpair("apple"))
print("Getting common pair for 'pear' - should be apple")
print(analysis.commonpair("pear"))
print("Getting common pair for 'banana' - should be peach")
print(analysis.commonpair("banana"))
print("Getting common pair for 'orange' - should be None")
print(analysis.commonpair("orange"))
print()
print()

print("Analysis for testfile2.txt")
analysis.load("testfile2.txt")
print("Getting total word count - should be 84")
print(analysis.countall())
print("Getting unique word count - should be 5")
print(analysis.countunique())
print("Getting common word out of ['apple','peach','pear'] - should be apple")
print(analysis.commonword(["apple","peach","pear"]))
print("Getting common word out of ['coconut','peach','banana'] - should be coconut")
print(analysis.commonword(["coconut","peach","banana"]))
print("Getting common word out of ['pear','banana'] - should be pear")
print(analysis.commonword(["pear","banana"]))
print("Getting common word out of ['apple','peach','pear','coconut','banana'] - should be coconut")
print(analysis.commonword(['apple','peach','pear','coconut','banana']))
print("Getting common word out of ['plum','orange'] - should be None")
print(analysis.commonword(['plum','orange']))
print("Getting common letter out of ['a','e','i','o','u'] - should be a")
print(analysis.commonletter(['a','e','i','o','u']))
print("Getting common letter out of ['c', 't', 'p'] - should be p")
print(analysis.commonletter(['c', 't', 'p']))
print("Getting common letter out of ['z','x','y'] - should be None")
print(analysis.commonletter(['z','x','y']))
print("Getting common pair for 'apple' - should be coconut or peach")
print(analysis.commonpair("apple"))
print("Getting common pair for 'pear' - should be apple")
print(analysis.commonpair("pear"))
print("Getting common pair for 'banana' - should be apple")
print(analysis.commonpair("banana"))
print("Getting common pair for 'orange' - should be None")
print(analysis.commonpair("orange"))
print()
print()

print("Analysis for testfile3.txt")
analysis.load("testfile3.txt")
print("Getting total word count - should be 86")
print(analysis.countall())
print("Getting unique word count - should be 5")
print(analysis.countunique())
print("Getting common word out of ['apple','peach','pear'] - should be peach")
print(analysis.commonword(["apple","peach","pear"]))
print("Getting common word out of ['coconut','peach','banana'] - should be peach")
print(analysis.commonword(["coconut","peach","banana"]))
print("Getting common word out of ['pear','banana'] - should be pear")
print(analysis.commonword(["pear","banana"]))
print("Getting common word out of ['apple','peach','pear','coconut','banana'] - should be peach")
print(analysis.commonword(['apple','peach','pear','coconut','banana']))
print("Getting common word out of ['plum','orange'] - should be None")
print(analysis.commonword(['plum','orange']))
print("Getting common letter out of ['a','e','i','o','u'] - should be a")
print(analysis.commonletter(['a','e','i','o','u']))
print("Getting common letter out of ['c', 't', 'p'] - should be c")
print(analysis.commonletter(['c', 't', 'p']))
print("Getting common letter out of ['z','x','y'] - should be None")
print(analysis.commonletter(['z','x','y']))
print("Getting common pair for 'apple' - should be peach")
print(analysis.commonpair("apple"))
print("Getting common pair for 'pear' - should be coconut or pear")
print(analysis.commonpair("pear"))
print("Getting common pair for 'banana' - should be peach")
print(analysis.commonpair("banana"))
print("Getting common pair for 'orange' - should be None")
print(analysis.commonpair("orange"))
print()
print()

print("Analysis for testfile4.txt")
analysis.load("testfile4.txt")
print("Getting total word count - should be 71")
print(analysis.countall())
print("Getting unique word count - should be 5")
print(analysis.countunique())
print("Getting common word out of ['apple','peach','pear'] - should be peach")
print(analysis.commonword(["apple","peach","pear"]))
print("Getting common word out of ['coconut','peach','banana'] - should be peach")
print(analysis.commonword(["coconut","peach","banana"]))
print("Getting common word out of ['pear','banana'] - should be pear")
print(analysis.commonword(["pear","banana"]))
print("Getting common word out of ['apple','peach','pear','coconut','banana'] - should be peach")
print(analysis.commonword(['apple','peach','pear','coconut','banana']))
print("Getting common word out of ['plum','orange'] - should be None")
print(analysis.commonword(['plum','orange']))
print("Getting common letter out of ['a','e','i','o','u'] - should be a")
print(analysis.commonletter(['a','e','i','o','u']))
print("Getting common letter out of ['c', 't', 'p'] - should be p")
print(analysis.commonletter(['c', 't', 'p']))
print("Getting common letter out of ['z','x','y'] - should be None")
print(analysis.commonletter(['z','x','y']))
print("Getting common pair for 'apple' - should be peach")
print(analysis.commonpair("apple"))
print("Getting common pair for 'pear' - should be peach")
print(analysis.commonpair("pear"))
print("Getting common pair for 'banana' - should be pear")
print(analysis.commonpair("banana"))
print("Getting common pair for 'orange' - should be None")
print(analysis.commonpair("orange"))
print()
print()

print("Analysis for testfile5.txt")
analysis.load("testfile5.txt")
print("Getting total word count - should be 99")
print(analysis.countall())
print("Getting unique word count - should be 5")
print(analysis.countunique())
print("Getting common word out of ['apple','peach','pear'] - should be apple")
print(analysis.commonword(["apple","peach","pear"]))
print("Getting common word out of ['coconut','peach','banana'] - should be banana")
print(analysis.commonword(["coconut","peach","banana"]))
print("Getting common word out of ['pear','banana'] - should be banana")
print(analysis.commonword(["pear","banana"]))
print("Getting common word out of ['apple','peach','pear','coconut','banana'] - should be apple")
print(analysis.commonword(['apple','peach','pear','coconut','banana']))
print("Getting common word out of ['plum','orange'] - should be None")
print(analysis.commonword(['plum','orange']))
print("Getting common letter out of ['a','e','i','o','u'] - should be a")
print(analysis.commonletter(['a','e','i','o','u']))
print("Getting common letter out of ['c', 't', 'p'] - should be p")
print(analysis.commonletter(['c', 't', 'p']))
print("Getting common letter out of ['z','x','y'] - should be None")
print(analysis.commonletter(['z','x','y']))
print("Getting common pair for 'apple' - should be banana")
print(analysis.commonpair("apple"))
print("Getting common pair for 'pear' - should be coconut, peach, or apple")
print(analysis.commonpair("pear"))
print("Getting common pair for 'banana' - should be apple")
print(analysis.commonpair("banana"))
print("Getting common pair for 'orange' - should be None")
print(analysis.commonpair("orange"))
