CFLAGS = -g -std=c99
CC = gcc

example1: example1.c
	$(CC) $(CFLAGS) example1.c -o example1

example2: example2.c
	$(CC) $(CFLAGS) example2.c -o example2

example3: example3.c
	$(CC) $(CFLAGS) example3.c -o example3

example4: example4.c
	$(CC) $(CFLAGS) example4.c -o example4

example5: example5.c
	$(CC) $(CFLAGS) example5.c -o example5

example6: example6.c
	$(CC) $(CFLAGS) example6.c -o example6

clean:
	rm -f *.o *.d a.out example1 example2 example3 example4 example5 example6




